betaCode: kraftbyalex

environment: "PROD"

host: "kraftcloud.dev"

database:
  database: "kraft"
  host: "kraft-db" # this points to the hosted db by default
  password: dontuseme
  rootPassword: changeme
  port: 3306
  user: kraft

  hosted:
    enabled: true
    image: registry.opensuse.org/opensuse/mariadb:11.8
    size: "4Gi"
