apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kraft-ingressroute
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - match: Host(`kraftcloud.dev`) && Path(`/api`)
    kind: Rule
    services:
    - name: kraft-cluster-manage
      port: 5000

  - match: Host(`kraftcloud.dev`) && Path(`/resources`)
    kind: Rule
    services:
    - name: kraft-resource-manage
      port: 5000

  - match: Host(`kraftcloud.dev`) && Path(`/auth`)
    kind: Rule
    services:
    - name: kraft-auth
      port: 5000

  - match: Host(`kraftcloud.dev`)
    kind: Rule
    services:
    - name: kraft-frontend
      port: 80
  tls:
    certResolver: le
