apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: kraft-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "100"
    cert-manager.io/cluster-issuer: issuer
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: kraftcloud.dev
    http:
      paths:
      - backend:
          service:
            name: kraft-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - secretName: kraft-tls
      hosts:
        - kraftcloud.dev

status:
  loadBalancer: {}
