apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: kraft-resource-manage
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "200"
spec:
  rules:
  - host: kraftcloud.dev
    http:
      paths:
      - backend:
          service:
            name: kraft-resource-manage
            port:
              number: 5000
        path: /resources
        pathType: Prefix
status:
  loadBalancer: {}
