apiVersion: v1
data:
  # Hey so this is important because local skips a lot of the authentication
  ENVIRONMENT: 'PROD'
  HOST: 'kraftcloud.dev'
  # JWT_SECRET: 'something-goes-here'
  NTFY_URL: 'https://notify.alexbissessur.dev'
  NTFY_TOPIC: 'kraft'
  NTFY_BASIC_AUTH: 'base64 encoding of <username:password>'

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: global-config
