# apiVersion: v1
# data:
#   JWT_SECRET: here
# kind: Secret
# metadata:
#   creationTimestamp: null
#   name: jwtsecret

# ---

# apiVersion: v1
# data:
#   NTFY_URL: 'https://notify.alexbissessur.dev'
#   NTFY_TOPIC: 'kraft'
#   NTFY_BASIC_AUTH: 'base64 encoding of <username:password>'
#   NTFY_TOKEN: 'if you use token rather than password'

# kind: ConfigMap
# metadata:
#   creationTimestamp: null
#   name: ntfysecret

# ---

# apiVersion: v1
# data:
#   DB_USED:
#   DB_DATABASE:
#   DB_HOST:
#   DB_PASSWORD:
#   DB_ROOT_PASSWORD:
#   DB_PORT:
#   DB_USER:
# kind: Secret
# metadata:
#   creationTimestamp: null
#   name: database-secrets
